"""empty message

Revision ID: 6fcd465aeb7b
Revises: 
Create Date: 2021-06-01 16:17:34.055141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fcd465aeb7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theather',
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('movieNm', sa.String(length=128), nullable=False),
    sa.Column('movieCd', sa.Integer(), nullable=False),
    sa.Column('openDt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('rank')
    )
    op.create_table('movie',
    sa.Column('movieCd_id', sa.Integer(), nullable=False),
    sa.Column('movieNm', sa.String(length=128), nullable=False),
    sa.Column('movieCd', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('audiCnt', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movieCd'], ['theather.movieCd'], ),
    sa.PrimaryKeyConstraint('movieCd_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie')
    op.drop_table('theather')
    # ### end Alembic commands ###
